### ISSUE TITLE
Transition crash issue

### ISSUE THREAD

**Issue by ParsifalC** [DeveloperLx/LxTabBarController#2]
To reproduce:
1.swipe to next page;
2.quickly tap the current tab bar item when transitioning.

And it crashed.
ps:set a longer TRANSITION_DURATION may help you to reproduce this issue.
here is the crash log:2015-07-06 16:12:43.178 LxTabBarControllerDemo[8929:1642292] **\* -[Transition retain]: message sent to deallocated instance 0x17000fee0

**Comment by ParsifalC** [comment]
I sent a pull request for this issue.
It seemed not a very elegant solution for this, but it worked.
#3

**Comment by JJetGu** [comment]
tabbar上面滑的话，会闪退

**Comment by ParsifalC** [comment]
@JJetGu  fixed.
here is the pull request.#5
